// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/* --- REAL DATABASE DEPENDENCY (Commented Out) ---
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
--- */

// --- DUMMY MOCK CLIENT TO RUN FRONTEND LOCALLY ---
const MOCK_PRODUCTS: any[] = [
  {
    id: "1", name: "Rose Pink Embroidered Anarkali", slug: "rose-pink-embroidered-anarkali",
    price: 7999, original_price: 9999, description: "A gorgeous rose pink anarkali with heavy thread embroidery and flared silhouette.",
    fabric: "Georgette with Cotton Lining", sizes: ["S", "M", "L", "XL"], colors: ["Rose Pink"],
    image_url: "/women-product1.jpg", images: ["/women-product2.jpg"], tag: "BESTSELLER",
    category: "Anarkali", stock_quantity: 5, is_active: true, created_at: "2026-03-01"
  },
  {
    id: "2", name: "Ivory Bridal Fusion Gown", slug: "ivory-bridal-fusion-gown",
    price: 14499, original_price: 18999, description: "A stunning ivory bridal fusion gown with intricate zardozi work and trail silhouette.",
    fabric: "Silk Organza", sizes: ["S", "M", "L", "XL"], colors: ["Ivory", "White"],
    image_url: "/women-product2.jpg", images: ["/women-product3.jpg"], tag: "TRENDING",
    category: "Bridal", stock_quantity: 3, is_active: true, created_at: "2026-03-02"
  },
  {
    id: "3", name: "Mauve Satin Kurta Set", slug: "mauve-satin-kurta-set",
    price: 5999, original_price: null, description: "A premium mauve satin kurta set with modern cuts and palazzo pants.",
    fabric: "Satin", sizes: ["S", "M", "L", "XL"], colors: ["Mauve", "Lavender"],
    image_url: "/women-product4.jpg", images: ["/women-product5.jpg"], tag: null,
    category: "Kurta Set", stock_quantity: 12, is_active: true, created_at: "2026-03-03"
  },
  {
    id: "4", name: "Burgundy Blazer & Skirt Set", slug: "burgundy-blazer-skirt-set",
    price: 9999, original_price: 12999, description: "A bold burgundy Indo-Western blazer paired with a flowing pleated skirt. Statement-making fusion fashion.",
    fabric: "Crepe with Luxe Detailing", sizes: ["S", "M", "L", "XL"], colors: ["Burgundy", "Wine"],
    image_url: "/women-product3.jpg", images: ["/women-product1.jpg"], tag: "TRENDING",
    category: "Blazer Set", stock_quantity: 8, is_active: true, created_at: "2026-03-04"
  },
  {
    id: "5", name: "Sage Green Chanderi Kurta", slug: "sage-green-chanderi-kurta",
    price: 4499, original_price: 5499, description: "A light and airy sage green chanderi kurta with gold block prints. Perfect for everyday elegance.",
    fabric: "Chanderi Silk", sizes: ["S", "M", "L", "XL"], colors: ["Sage Green"],
    image_url: "/women-product5.jpg", images: ["/women-product6.jpg"], tag: null,
    category: "Kurta", stock_quantity: 20, is_active: true, created_at: "2026-03-05"
  },
  {
    id: "6", name: "Navy Blue Blazer Suit", slug: "navy-blue-blazer-suit",
    price: 11500, original_price: 14999, description: "A sophisticated navy blue Indo-Western blazer suit with golden brooch detail. Power dressing redefined.",
    fabric: "Premium Twill", sizes: ["S", "M", "L", "XL"], colors: ["Navy Blue"],
    image_url: "/women-product6.jpg", images: ["/women-product3.jpg"], tag: "BESTSELLER",
    category: "Blazer Suit", stock_quantity: 6, is_active: true, created_at: "2026-03-06"
  }
];

const MOCK_DATA: Record<string, any[]> = {
  products: MOCK_PRODUCTS,
  reviews: [],
  profiles: [],
  wishlist: [],
  coupons: [],
  addresses: [],
  orders: [],
  order_items: [],
  contact_messages: [],
  user_roles: [],
};

// A builder that mimics the Supabase query chain
class MockQueryBuilder {
  private table: string;
  private filters: Array<{ type: string; col: string; val: any }> = [];
  private isSingle = false;
  private isMaybeSingle = false;

  constructor(table: string) {
    this.table = table;
  }

  select() { return this; }
  order() { return this; }
  limit() { return this; }
  insert() { return this; }
  update() { return this; }
  delete() { return this; }
  upsert() { return this; }

  eq(col: string, val: any) {
    this.filters.push({ type: 'eq', col, val });
    return this;
  }

  ilike(col: string, pattern: string) {
    this.filters.push({ type: 'ilike', col, val: pattern });
    return this;
  }

  gte(col: string, val: any) {
    this.filters.push({ type: 'gte', col, val });
    return this;
  }

  lte(col: string, val: any) {
    this.filters.push({ type: 'lte', col, val });
    return this;
  }

  in() { return this; }

  single() {
    this.isSingle = true;
    return this;
  }

  maybeSingle() {
    this.isMaybeSingle = true;
    return this;
  }

  then(resolve: (value: any) => any, reject?: (reason?: any) => any) {
    let rows = MOCK_DATA[this.table] || [];

    // Apply filters
    for (const f of this.filters) {
      if (f.type === 'eq') {
        rows = rows.filter((r: any) => r[f.col] === f.val);
      } else if (f.type === 'ilike') {
        const pattern = String(f.val).replace(/%/g, '').toLowerCase();
        rows = rows.filter((r: any) => String(r[f.col] || '').toLowerCase().includes(pattern));
      } else if (f.type === 'gte') {
        rows = rows.filter((r: any) => (r[f.col] ?? 0) >= f.val);
      } else if (f.type === 'lte') {
        rows = rows.filter((r: any) => (r[f.col] ?? 0) <= f.val);
      }
    }

    let result: any;
    if (this.isSingle) {
      result = { data: rows[0] || null, error: rows[0] ? null : { message: 'Not found' } };
    } else if (this.isMaybeSingle) {
      result = { data: rows[0] || null, error: null };
    } else {
      result = { data: rows, error: null };
    }

    return Promise.resolve(result).then(resolve, reject);
  }
}

// Provides an implementation that prevents frontend crashes when calling DB methods
export const supabase = {
  from: (table: string) => new MockQueryBuilder(table),
  auth: {
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => { } } } }),
    getSession: () => Promise.resolve({ data: { session: null } }),
    signOut: () => Promise.resolve(),
    signUp: () => Promise.resolve({ data: null, error: { message: 'DB Disabled' } }),
    signInWithPassword: () => Promise.resolve({ data: null, error: { message: 'DB Disabled' } }),
  },
  storage: {
    from: () => new MockQueryBuilder('storage'),
  }
} as any;